server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost/usuario?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=GMT
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: usuario-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
